services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
    command: serve

  web:
    image: nginx:1.27.4-alpine
    volumes:
      - ./src:/usr/share/nginx/html
    ports:
      - 3001:80
